/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import hospital.HospSys;
import javax.swing.JComboBox;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author Iqbal Karim
 */
public class MainFrame extends javax.swing.JFrame {
    
    PatientsFrame patients = new PatientsFrame(this);
    rsfStaff rsf = new rsfStaff(this);
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void clear(){
        fnamField.setText("");
        lnameField.setText("");
        emailField.setText("");
        pnumField.setText("");
        addressField.setText("");
        countField.setText("");
        multiplierField.setText("");
        staffIDField.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        countLabel = new javax.swing.JLabel();
        multiplierLabel = new javax.swing.JLabel();
        pnumField = new javax.swing.JTextField();
        fnamField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        countField = new javax.swing.JTextField();
        multiplierField = new javax.swing.JTextField();
        lnameField = new javax.swing.JTextField();
        staffIDField = new javax.swing.JTextField();
        TypeCombo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        DisplayCombo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        searchdelete = new javax.swing.JButton();
        statusCombo = new javax.swing.JComboBox<>();
        status = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital Staff System");

        jLabel1.setText("FIrst Name:");

        jLabel2.setText("Last Name:");

        jLabel3.setText("Email:");

        jLabel4.setText("Staff ID:");

        jLabel5.setText("Address");

        jLabel6.setText("Phone Number:");

        countLabel.setText("Hours:");

        multiplierLabel.setText("Wage:");

        pnumField.setText("+90-");

        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });

        TypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nurse", "Surgeon", "Consultant" }));
        TypeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeComboActionPerformed(evt);
            }
        });

        jLabel9.setText("Staff Type");

        output.setColumns(20);
        output.setRows(5);
        jScrollPane1.setViewportView(output);

        DisplayCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Nurses", "Surgeons", "Consultants" }));
        DisplayCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayComboActionPerformed(evt);
            }
        });

        jLabel10.setText("Display:");

        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        searchdelete.setText("SEARCH/DELETE");
        searchdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchdeleteActionPerformed(evt);
            }
        });

        statusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "true", "false" }));

        status.setText("Liscence:");

        jButton1.setText("DISPLAY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("SWITCH TO  PATIENT SYSTEMS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("DISPLAY HOSPITAL FINANCES");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TypeCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pnumField)
                                        .addComponent(fnamField)
                                        .addComponent(addressField)
                                        .addComponent(emailField)
                                        .addComponent(staffIDField)
                                        .addComponent(lnameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(countLabel)
                                        .addComponent(multiplierLabel)
                                        .addComponent(status))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(countField)
                                        .addComponent(multiplierField)
                                        .addComponent(statusCombo, 0, 150, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(searchdelete)))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(DisplayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)))
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(DisplayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(fnamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(staffIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(pnumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(countLabel)
                            .addComponent(countField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(multiplierLabel)
                            .addComponent(multiplierField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(status))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(add)
                            .addComponent(searchdelete)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void TypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeComboActionPerformed
        String type = (String)TypeCombo.getSelectedItem();
        switch (type) {
            case "Surgeon":
                countLabel.setText("Num Surgeries:");
                multiplierLabel.setText("Per Surgery:");
                status.setText("Speciality:");
                String cmbs[] = new String[5];
                cmbs[0] = "Cardiologist";
                cmbs[1] = "Orthodontist";
                cmbs[2] = "Neurosurgeon";
                cmbs[3] = "Obstetrician";
                cmbs[4] = "Orthopaedic";

                statusCombo.setModel(new DefaultComboBoxModel(cmbs));
                break;
            case "Consultant":
                countLabel.setText("Num Consultancies:");
                multiplierLabel.setText("Per Consultancy:");
                status.setText("Speciality:");
                String cmbc[] = new String[4];
                cmbc[0] = "Cardiologist";
                cmbc[1] = "Pediatrician";
                cmbc[2] = "Dermatologists";
                cmbc[3] = "Nutritionist";
                statusCombo.setModel(new DefaultComboBoxModel(cmbc));
                break;
            case "Nurse":
                countLabel.setText("Hours:");
                multiplierLabel.setText("Wage:");
                status.setText("Lisence:");
                String cmbn[] = new String[2];
                cmbn[0] = "true";
                cmbn[1] = "false";
                statusCombo.setModel(new DefaultComboBoxModel(cmbn));

                break;
            default:
                break;
        }
    }//GEN-LAST:event_TypeComboActionPerformed

    private void DisplayComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayComboActionPerformed

    }//GEN-LAST:event_DisplayComboActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        String fname = fnamField.getText();
        String lname = lnameField.getText();
        String email = emailField.getText();
        String phone = pnumField.getText();
        String address = addressField.getText();    
        String status = (String)statusCombo.getSelectedItem();
        String str = "";
        
        if (fname.equals("") || lname.equals("") || staffIDField.getText().equals("") || email.equals("") || phone.equals("") || 
                address.equals("") || countField.getText().equals("") || multiplierField.getText().equals("")){
            str = ("Please fill all necessary fields!");
        }
        else{
            int count = Integer.parseInt(countField.getText());
            double multiplier = Double.parseDouble(multiplierField.getText());
            int id = Integer.parseInt(staffIDField.getText()); 

            String type = (String)TypeCombo.getSelectedItem();
            str = HospSys.addStaff(type, id, fname, lname, email, phone, address, count, status, multiplier);
            clear();
        }
        output.setText(str);
    }//GEN-LAST:event_addActionPerformed

    private void searchdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchdeleteActionPerformed
        if (HospSys.staff.isEmpty())
            output.setText("Enter staff members to search and delete");
        else{
            rsf.getIDcmb().setModel(new DefaultComboBoxModel(HospSys.getIDs()));
            rsf.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_searchdeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String disp = (String)DisplayCombo.getSelectedItem();
        output.setText(HospSys.displayStaff(disp));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        patients.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        hospitalFinances hospFinance = new hospitalFinances(this);
        hospFinance.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DisplayCombo;
    private javax.swing.JComboBox<String> TypeCombo;
    private javax.swing.JButton add;
    private javax.swing.JTextField addressField;
    private javax.swing.JTextField countField;
    private javax.swing.JLabel countLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField fnamField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lnameField;
    private javax.swing.JTextField multiplierField;
    private javax.swing.JLabel multiplierLabel;
    private javax.swing.JTextArea output;
    private javax.swing.JTextField pnumField;
    private javax.swing.JButton searchdelete;
    private javax.swing.JTextField staffIDField;
    private javax.swing.JLabel status;
    private javax.swing.JComboBox<String> statusCombo;
    // End of variables declaration//GEN-END:variables
}
